name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configs: [Release, Debug]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install dependencies
      working-directory: native
      shell: bash
      run: |
        bash setup.sh
    - name: Setup Cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.24.x'
    - name: Build project
      shell: bash
      working-directory: native
      if: matrix.os != 'macos-latest'
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE:STRING=vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE:STRING=${{ matrix.configs }} -B build -S .
        cmake --build build --config ${{ matrix.configs }} --target all --
    - name: Build project (macOS)
      shell: bash
      working-directory: native
      if: matrix.os == 'macos-latest'
      run: |
        cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCMAKE_BUILD_TYPE:STRING=${{ matrix.configs }} -B build -S .
        cmake --build build --config ${{ matrix.configs }} --target all --
    - uses: actions/upload-artifact@v2
      with:
        path: build/*.tar.gz
        name: artifact_${{ matrix.os }}_${{ matrix.configs }}.tar.gz
